upgrade

tap caskroom/fonts
tap homebrew/dupes
tap homebrew/python
tap homebrew/science
tap phinze/cask
tap tldr-pages/tldr

cask 'font-source-han-code-jp'

brew 'coreutils'
brew 'curl'
brew 'freetype'
brew 'gibo'
brew 'git'
brew 'highlight'
brew 'hub'
brew 'libevent'
brew 'libpng'
brew 'libtiff'
brew 'libtool'
brew 'lua'
brew 'nkf'
brew 'oniguruma'
brew 'openssl'
brew 'pidcat'
brew 'readline'
brew 'reattach-to-user-namespace'
brew 'tldr'
brew 'tmux'
brew 'tree'
brew 'vim' args: ['with-lua']
brew 'xz'
brew 'zsh'
brew 'carthage'

clean
