#!/bin/sh

# install necessary software
sudo pip install diff-highlight mycli

# copy some dotfiles
cp ~/.dotfiles/tmux/tmux.conf ~/.tmux.conf
cp ~/.dotfiles/zsh/zshrc.zsh ~/.zshrc
cp ~/.dotfiles/vim/vimrc ~/.vimrc
cp ~/.dotfiles/gitfile/gitignore ~/.gitignore
cp ~/.dotfiles/gitfile/gitconfig ~/.gitconfig
cp ~/.dotfiles/gitfile/gitmessage ~/.gitmessage

