#!/bin/sh

# シンボリックリンク削除
unlink ~/.zshrc
unlink ~/.vimrc
unlink ~/.gitignore
unlink ~/.gitignore 
unlink ~/.gitmessage.txt 
unlink ~/.tmux.conf 

# 不要ファイル削除
rm -rf ~/.vim/ 
rm -rf ~/Developer/dircolors-solarized/ 

