[[custom_plugins]]
  name = "dracula/vim"
[options]
  colorscheme = "dracula"
  colorscheme_bg = "dark"
  enable_tabline_filetype_icon = true

[[layers]]
  name = "autocomplete"
  auto-completion-return-key-behavior = "complete"
  auto-completion-tab-key-behavior = "cycle"

[[layers]]
  name = "shell"
  default_position = "top"
  default_height = 30

[[layers]]
  name = "lang#javascript"

[[layers]]
  name = "lang#ruby"

[[layers]]
  name = "lang#go"
